services:
  - type: web
    name: my-static-site
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    routes:
      - src: /static/*
        dest: /static/*-
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /
    autoDeploy: true
    